services:
  db:
    image: postgres:15
    container_name: rempay-db
    restart: always
    environment:
      POSTGRES_DB: gateway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: rempay-container
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/gateway
    ports:
      - "3001:3000"
    # For production, do not mount local code or node_modules
    # Command is set in Dockerfile

volumes:
  db_data:
