# Default configuration
 mtn:
   base: "https://sandbox.momodeveloper.mtn.com"
   subscription_key: "2551a785e77045b1816e58a9f8f3f5a2"
   target_environment: "sandbox"
   x_reference_id: "2a9e64b4-42a3-4c0e-bf78-6b7a7d6f9e3b"
   api_key: "83a3772cee884a3ab75621ef4b2895cd"
   webhook_key: "your_webhook_secret_key"
db:
  host: localhost
  port: 5433
  username: postgres
  password: postgres
  database: gateway
