mtn:
  base: "https://sandbox.momodeveloper.mtn.com"
  collection:
    subscription_key: "2551a785e77045b1816e58a9f8f3f5a2"
    target_environment: "sandbox"
    x_reference_id: "bf8318a6-2db3-4fe1-98f2-c002cefdd4d6"
    api_key: "21e3318d9b6a4f64a56a7209ddf83003"
    test_msisdn: "46733123453" # MTN MoMo Sandbox success test number
  disbursement:
    subscription_key: "eb49dfde65824998888a99c0b8a06b55"
    target_environment: "sandbox"
    x_reference_id: "d525968f-00df-416f-839f-f838b1fb7a14"
    api_key: "ef88782b087d4d7d830153174ec5f6bb"
db:
  host: db
  port: 5432
  username: postgres
  password: postgres
  database: gateway
olympus:
  link: "https://api.olympustech.example.com/mtn/details?"
