mtn:
  base: "https://sandbox.momodeveloper.mtn.com"
  subscription_key: "2551a785e77045b1816e58a9f8f3f5a2"
  target_environment: "sandbox"
  x_reference_id: "bf8318a6-2db3-4fe1-98f2-c002cefdd4d6"
  api_key: "21e3318d9b6a4f64a56a7209ddf83003"
  test_msisdn: "46733123453" # MTN MoMo Sandbox success test number
db:
  host: localhost
  port: 5433
  username: postgres
  password: postgres
  database: gateway
olympus:
  link: "https://api.olympustech.example.com/mtn/details?"
