mtn:
  base: "https://sandbox.momodeveloper.mtn.com"
  collection:
    subscription_key: "2551a785e77045b1816e58a9f8f3f5a2"
    target_environment: "sandbox"
    x_reference_id: "2a9e64b4-42a3-4c0e-bf78-6b7a7d6f9e3b"
    api_key: "83a3772cee884a3ab75621ef4b2895cd"
  disbursement:
    subscription_key: "eb49dfde65824998888a99c0b8a06b55"
    target_environment: "sandbox"
    x_reference_id: "bf8318a6-2db3-4fe1-98f2-c002cefdd4d6"
    api_key: "21e3318d9b6a4f64a56a7209ddf83003"
db:
  host: prod-db
  port: 5432
  username: produser
  password: prodpass
  database: gateway_prod
